#pragma once

#include "kizuri/Core.hpp"
#include "kizuri/core/Log.hpp"
#include "kizuri/core/LogHistory.hpp"
#include "kizuri/core/Application.hpp"
#include "kizuri/core/FileDialog.hpp"
#include "kizuri/core/Layer.hpp"
#include "kizuri/core/Window.hpp"
#include "kizuri/core/Input.hpp"
#include "kizuri/core/Event.hpp"
#include "kizuri/core/Timestep.hpp"
#include "kizuri/core/ImGuiLayer.hpp"
#include "kizuri/core/UUID.hpp"
#include "kizuri/core/EmbeddedContent.hpp"

#include "kizuri/renderer/Renderer.hpp"
#include "kizuri/renderer/Renderer2D.hpp"
#include "kizuri/renderer/Renderer3D.hpp"
#include "kizuri/renderer/GraphicsSettings.hpp"
#include "kizuri/renderer/TextRenderer.hpp"
#include "kizuri/renderer/RenderCommand.hpp"
#include "kizuri/renderer/Camera.hpp"
#include "kizuri/renderer/Shader.hpp"
#include "kizuri/renderer/Texture.hpp"
#include "kizuri/renderer/Buffer.hpp"
#include "kizuri/renderer/Framebuffer.hpp"

#include "kizuri/ecs/Scene.hpp"
#include "kizuri/ecs/Entity.hpp"
#include "kizuri/ecs/Components.hpp"
#include "kizuri/scene/SceneSerializer.hpp"
#include "kizuri/scene/Prefab.hpp"
#include "kizuri/scene/EditorHistory.hpp"
#include "kizuri/project/Project.hpp"

#include "kizuri/scripting/NativeScript.hpp"
#include "kizuri/scripting/ScriptRegistry.hpp"
#include "kizuri/scripting/ScriptEngine.hpp"

#include "kizuri/audio/AudioEngine.hpp"

#include "kizuri/assets/AssetManager.hpp"
#include "kizuri/project/GameExporter.hpp"
