
if(NOT DEFINED OUTPUT_FILE OR NOT DEFINED MANIFEST_FILE)
    message(FATAL_ERROR "EmbedContent.cmake requer OUTPUT_FILE e MANIFEST_FILE")
endif()

file(READ "${MANIFEST_FILE}" MANIFEST)
string(REPLACE "\n" ";" LINES "${MANIFEST}")

set(OUTPUT "#pragma once\n#include <cstddef>\n#include <cstdint>\n\nnamespace kizuri {\nnamespace detail {\n\nstruct EmbeddedFileEntry {\n    const char* Name;\n    const std::uint8_t* Data;\n    std::size_t Size;\n};\n\n")

set(INDEX 0)
foreach(line IN LISTS LINES)
    string(STRIP "${line}" line)
    if(line STREQUAL "" OR line MATCHES "^#")
        continue()
    endif()
    string(FIND "${line}" "\t" SEP)
    if(SEP EQUAL -1)
        message(FATAL_ERROR "Linha de manifest inválida (esperava 'nome<TAB>caminho'): ${line}")
    endif()
    string(SUBSTRING "${line}" 0 ${SEP} NAME)
    math(EXPR PATH_START "${SEP} + 1")
    string(SUBSTRING "${line}" ${PATH_START} -1 PATH)

    if(NOT EXISTS "${PATH}")
        message(FATAL_ERROR "Arquivo do manifest não existe: ${PATH}")
    endif()

    file(READ "${PATH}" HEX HEX)
    string(LENGTH "${HEX}" HEXLEN)
    math(EXPR FILESIZE "${HEXLEN} / 2")

    set(CHUNK_CHARS 4096)
    set(OFF 0)
    string(APPEND OUTPUT "inline const char kRes_${INDEX}[] =\n")
    while(OFF LESS HEXLEN)
        string(SUBSTRING "${HEX}" ${OFF} ${CHUNK_CHARS} SUB)
        string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "\\\\x\\1" SUB_ESC "${SUB}")
        string(APPEND OUTPUT "    \"${SUB_ESC}\"\n")
        math(EXPR OFF "${OFF} + ${CHUNK_CHARS}")
    endwhile()
    string(APPEND OUTPUT ";\ninline constexpr std::size_t kResSize_${INDEX} = ${FILESIZE};\n\n")
    math(EXPR INDEX "${INDEX} + 1")
endforeach()

string(APPEND OUTPUT "inline const EmbeddedFileEntry kEmbeddedFiles[] = {\n")
set(INDEX 0)
foreach(line IN LISTS LINES)
    string(STRIP "${line}" line)
    if(line STREQUAL "" OR line MATCHES "^#")
        continue()
    endif()
    string(FIND "${line}" "\t" SEP)
    string(SUBSTRING "${line}" 0 ${SEP} NAME)
    string(APPEND OUTPUT "    { \"${NAME}\", reinterpret_cast<const std::uint8_t*>(kRes_${INDEX}), kResSize_${INDEX} },\n")
    math(EXPR INDEX "${INDEX} + 1")
endforeach()
string(APPEND OUTPUT "};\n\ninline constexpr std::size_t kEmbeddedFileCount = ${INDEX};\n\n} // namespace detail\n} // namespace kizuri\n")

file(WRITE "${OUTPUT_FILE}" "${OUTPUT}")
message(STATUS "EmbedContent.cmake: ${INDEX} arquivo(s) embutido(s) em ${OUTPUT_FILE}")
